### ISSUE TITLE
Int64 Flag

### ISSUE THREAD

**Issue by saturnism** [codegangsta/cli#165] opened 2015-01-06 02:15 UTC
Current version handles Int flag.  It'd be useful to handle Int64 as well.

**Comment by jszwedko** [comment] 2015-01-08 21:22
I'm going to close this as a duplicate of #90, but I agree that this library should at least have all of the types supported by the standard library `flag` package (which includes `Int64`). I'll try to implement the missing ones soon.

**Closed** 2015-01-08 21:22 UTC
