### ISSUE TITLE
Global Flags are not accessible in Before action

### ISSUE THREAD

**Issue by agarwalpradeep123** [codegangsta/cli#247] opened 2015-06-22 14:50 UTC
I am using codegangsta/cli as below,

app := cli.NewApp()
	app.Name = "test"
	app.Usage = "Command Line"
	app.Version = "0.1"
	app.Before = setLogLevel
	app.Flags = []cli.Flag{
		cli.BoolFlag{
			Name:  "debug, d",
			Usage: "Enable debug logging",
		},
	}

app.Commands = []cli.Command{
		{
			Name:    "connect",
			Aliases: []string{"c"},
			Action: connect,
		},
}

Now when I pass global flag as below,
test -d connect
But in Before action value of "debug" flag is still false

**Comment by wrouesnel** [comment] 2015-06-25 01:27
How are you access the flag?
If you do c.GlobalBool("debug"") then it won't be right - because it's not a global in the Before context.

I tried something similar just now doing c.Bool("debug") in a Before function and it works.

**Comment by agarwalpradeep123** [comment] 2015-06-25 03:59
Thanks for answer. After using c.Bool("debug") in Before function, I could get expected response. So on same lines I think in Before function I should use c.IsSet(...) instead of c.GlobalIsSet(...)

Thanks.

**Comment by jszwedko** [comment] 2015-07-01 03:18
@agarwalpradeep123 this was actually a regression fixed by https://github.com/codegangsta/cli/pull/253 -- the old behavior was that `GlobalX` was required, but that was lost and has been re-added. Thanks for raising this!

**Closed by jszwedko** 2015-07-01 03:18 UTC
