### ISSUE TITLE
DEPRECATED Action signature despite correct action signature

### ISSUE THREAD

**Issue by huguesalary** [codegangsta/cli#382] opened 2016-05-02 22:04 UTC
Despite changing my `app.Action` to the correct function signature, I get the `DEPRECATED Action signature.  Must be cli.ActionFunc.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature` error.

My code:
```
func main() {
	app := cli.NewApp()
	app.Action = func(c *cli.Context) error {
		return nil
	}
    app.Run(os.Args)
}
```

**Comment by meatballhat** [comment] 2016-05-02 22:14
@huguesalary Thanks for the report.  I cannot reproduce this with your example code (OS X, go1.5.2).  Can you provide your execution environment as well?  Thanks in advance! 😺

**Comment by huguesalary** [comment] 2016-05-02 22:20
My bad. I just commented out my `app.Action` and I still get the error message. It might be coming from a library I'm using. (I'm using the docker-machine library extensively, I bet it comes from there).

Is there anyway this error message could be made more specific to help the developer finding where exactly in the code this is happening?

Other than that, this bug is invalid.

**Comment by meatballhat** [comment] 2016-05-02 22:55
@huguesalary we could maybe play around with `runtime.Caller(n)` (???) ... but I'd assume that's error-prone, seldom will be accurate, other bad stuff

**Comment by meatballhat** [comment] 2016-05-03 00:04
I'm closing this out, but I'm happy to continue a discussion about how to improve deprecations in a new issue 😺

**Closed by meatballhat** 2016-05-03 00:04 UTC
Labels: bug

**Comment by jszwedko** [comment] 2016-05-03 04:25
`docker/machine` does make use of `codegangsta/cli` though they vendor it (https://github.com/docker/machine/tree/master/vendor/github.com/codegangsta/cli). May be worth issuing a PR over there to update the library and its usage.
