### ISSUE TITLE
Using undefined commands should cause an error

### ISSUE THREAD

**Issue by sandlerben** [codegangsta/cli#260] opened 2015-07-15 22:37 UTC
Let's say I have an app called `app` and it is defined with the following flags and no subcommands:

```
app.Flags = []cli.Flag{
	cli.StringFlag{
		Name:  "url, u",
		Value: "http://localhost:8080",
		Usage: "base url of your go program",
	},
}
```

If I call the command with an undefined subcommand like `hi`, the program just runs (I think it should return an error).

```
$ app hi
running app...
finished running app!
```

**Comment by jszwedko** [comment] 2015-07-17 16:12
@sandlerben I wasn't able to reproduce this issue, it should say `No help topic for 'hi'`. Can you provide a full source file I could run?
`

**Comment by ybogdanov** [comment] 2015-07-24 06:43
Hey, I have the same issue, but do want to add some extra:
In case of undefined command, such as `app hi`, program should exit with code 1. But there is no way to do it, because `app.Run` does not return error in this case. It just outputs `No help topic for 'hi'` to stdout. I think `app.Run` should return error to that it can be catched in the `main` program like this:

```go
if err := app.Run(os.Args); err != nil {
    fmt.Println(err)
    os.Exit(1)
}
```

**Comment by ybogdanov** [comment] 2015-07-24 06:57
Found a workaround:

```
app.CommandNotFound = func(ctx *cli.Context, command string) {
  fmt.Printf("Command not found: %v\n", command)
  os.Exit(1)
}
```

**Comment by sandlerben** [comment] 2015-07-27 16:49
@jszwedko now that my project is open-sourced I can give the real example.

```bash
$ go-torch hi
INFO[0000] Profiling ...
```

There is no hi command. See my code [here](https://github.com/uber/go-torch) and try it for yourself.

**Comment by jszwedko** [comment] 2015-07-27 23:29
@sandlerben unfortunately, because you have a default action defined (https://github.com/uber/go-torch/blob/master/main.go#L140), it wouldn't be possible to determine if your code accepts arguments or if that should be considered an invalid command.

**Comment by jszwedko** [comment] 2016-05-03 05:07
Closing out, but the workaround is to just check in the default action if you were passed any arguments, erroring if so.

Support for argument specification is embodied in #240

**Closed by jszwedko** 2016-05-03 05:07 UTC

**Comment by jszwedko** [comment] 2016-05-03 05:12
@ybogdanov your issue is encapsulated in #276
